[UPD] l10n_nl_rgs: Changes for accounts and added reconcile models
onesteinbv/addons-generic pull request #41
Opened 2024-04-24 08:36 UTC by ByteMeAsap

This includes following changes:
1.Account Margin call does not have Group. The Group should be G.K (achieved this by changing account code)
2.Account 1103105 should be set to inactive (deprecated)
3.Changes for account group sorting (used code_prefix_start,sort_code as the order).
4.Added Default reconciliation models with RGS chart of accounts

2024-04-24 08:37 UTC, ByteMeAsap commented
As per @ThijsvOers , there are some changes to be made for the reconciliation models

2024-04-29 08:45 UTC, ThijsvOers approved these changes
Checked the requested changes and they are all there

2024-05-01 14:08 UTC, andreschenkels requested changes
There needs to be some sort of migration script dealing with the 1103400 -> 1103007 change and the change in 1103105.

2024-05-02 06:29 UTC, ByteMeAsap commented
@andreschenkels , I have added the migration scripts as suggested

2024-05-02 08:49 UTC, andreschenkels approved these changes
LGTM

2024-05-02 10:40 UTC, merged