Changes to use mollie mandates instead of subscriptions for recurring payments
onesteinbv/addons-generic pull request #55
Opened 2024-07-04 13:19 UTC by ByteMeAsap

2024-08-20 10:01 UTC, tarteo requested changes
In case of an direct payment on an invoice should we filter it also in this method `_mollie_get_supported_methods` ?

2024-08-20 10:01 UTC, tarteo commented on sale_recurring_payment/models/sale_subscription.py
>                  raise UserError(
This can be removed now

2024-08-20 10:01 UTC, tarteo commented on sale_recurring_payment/models/sale_subscription.py
> +    def cron_terminate_payment_provider_mandates(self):
Is this cron job required? I ask this because it already revokes the mandate at the write method

2024-08-20 10:01 UTC, tarteo commented on sale_recurring_payment_mollie/models/payment_transaction.py
> +                done_payment_transaction = (
Most recurring payments are deferred. Therefore shouldn't this last part of the method always be done if the payment is in state pending or authorized?

2024-08-20 10:02 UTC, tarteo commented on sale_recurring_payment/models/sale_subscription.py
> +                            "Terminated subscriptions with payment provider mandate also terminated cannot be "
A UX consideration is to recreate the mandate here if this is the case instead of throwing an user error. Non-blocking issue

2024-08-21 05:58 UTC, ByteMeAsap commented on sale_recurring_payment/models/sale_subscription.py
> +    def cron_terminate_payment_provider_mandates(self):
Removed

2024-08-21 05:58 UTC, ByteMeAsap commented on sale_recurring_payment/models/sale_subscription.py
>                  raise UserError(
Removed

2024-08-21 05:59 UTC, ByteMeAsap commented on sale_recurring_payment_mollie/models/payment_transaction.py
> +                done_payment_transaction = (
I would keep it like this, as when the payment status is updated on mollie end, it would be updated here through webhook

2024-08-21 06:07 UTC, ByteMeAsap commented
> In case of an direct payment on an invoice should we filter it also in this method `_mollie_get_supported_methods` ?

I think that's logical ,I have added it

2024-08-21 06:10 UTC, ByteMeAsap commented on sale_recurring_payment/models/sale_subscription.py
> +    def cron_terminate_payment_provider_mandates(self):
But one thing, can we change action_close_subscription to close_subscription with or without default reason in the cron_subscription_management function? .I saw that you have already mentioned the same in  https://github.com/OCA/contract/issues/1057

2024-08-21 11:16 UTC, tarteo commented on sale_recurring_payment_mollie/models/payment_transaction.py
> +                done_payment_transaction = (
Ah yes, you're correct!

2024-08-21 11:19 UTC, merged